### ISSUE TITLE
Failed to run netopeer-configurator

### ISSUE THREAD

**Issue by yunyuaner** [CESNET/netopeer#91]
jiag@agent-VirtualBox:~/netconf/usr/bin$ ./python3 ./netopeer-configurator
Traceback (most recent call last):
  File "./netopeer-configurator", line 10, in <module>
    from netopeer.ncmodule import NCModuleError
  File "/home/jiag/netconf/usr/lib/python3.4/site-packages/netopeer/__init__.py", line 28, in <module>
    consolidate_paths(config.paths)
AttributeError: 'module' object has no attribute 'paths'

I've no experience in Python, can anybody help me to check the error prompt?

**Comment by rkrejci** [comment]
I believe that the configurator does not work with python3. You will probably need python2.
